/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_profiler_free: (a: number, b: number) => void;
export const debug_force_panic: () => void;
export const profiler_begin_sample: (a: number, b: number) => void;
export const profiler_begin_sample_pe: (a: number, b: number) => void;
export const profiler_c: (a: number) => number;
export const profiler_cancel_sample: (a: number) => void;
export const profiler_database_size: (a: number) => number;
export const profiler_feed: (a: number, b: number, c: number) => number;
export const profiler_feed_r1: (a: number, b: number, c: number) => number;
export const profiler_feed_r2: (a: number, b: number, c: number) => number;
export const profiler_finish_sample: (a: number) => [number, number, number, number];
export const profiler_k: (a: number) => number;
export const profiler_new: (a: number, b: number) => [number, number, number];
export const profiler_pair_lag: (a: number) => number;
export const profiler_pair_pending_r1: (a: number) => number;
export const profiler_pair_pending_r2: (a: number) => number;
export const profiler_pair_queued_r1: (a: number) => number;
export const profiler_pair_queued_r2: (a: number) => number;
export const profiler_profile: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const profiler_profile_pe: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const profiler_sample_done: (a: number) => number;
export const profiler_sample_halted: (a: number) => number;
export const profiler_sample_invalid: (a: number) => number;
export const profiler_sample_reads: (a: number) => number;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
