#!/usr/bin/env bash
#
# Write data/screening/manifest.tsv to stdout, entirely from the files it
# describes. Nothing here is typed by hand.
#
#   scripts/write_screening_manifest.sh [DIR] > DIR/manifest.tsv
#   scripts/check_screening_manifest.sh          # fails if the two differ
#
# WHY IT EXISTS
# -------------
# The hand-written manifest said "2 genomes under the 50-kmer profile floor" for
# the c=4000 build and "121" for c=8000. The files actually held 4 and 140. A
# manifest that is not measured is not evidence, and it was the *recommended*
# variant whose number was wrong. Every column below is now read back off the
# file: bytes and sha256 with coreutils, everything else from
# `syldb-reduce --list`, whose field names (n=, c=, k=, min_genome_kmers=,
# below_floor=) are pinned by a unit test in the tool.
#
set -euo pipefail
export PATH="$HOME/.cargo/bin:$PATH"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIR="${1:-$ROOT/data/screening}"
REDUCE="${REDUCE:-$ROOT/sylph-wasm/target/release/syldb-reduce}"
FLOOR="${FLOOR:-50}"

[ -x "$REDUCE" ] || {
  echo "syldb-reduce not built: (cd $ROOT/sylph-wasm && cargo build --release --bin syldb-reduce)" >&2
  exit 2
}
shopt -s nullglob
FILES=("$DIR"/*.syldb)
[ ${#FILES[@]} -gt 0 ] || { echo "no .syldb in $DIR" >&2; exit 2; }

field() { printf '%s\n' "$1" | tr '\t' '\n' | awk -F= -v k="$2" '$1==k{print $2; exit}'; }

note_for() {
  case "$1" in
    *-derep.syldb) echo "one genome per GTDB species across catalogues; sketches left under the ${FLOOR}-kmer floor were dropped at build time (they are undetectable: get_stats returns None below profile's --min-number-kmers)" ;;
    *)             echo "NOT dereplicated across catalogues - kept for comparison only, do not ship" ;;
  esac
}

cat <<EOF
# data/screening/manifest.tsv — GENERATED by scripts/write_screening_manifest.sh.
# Do not edit by hand: scripts/check_screening_manifest.sh regenerates it from the
# files and fails on any difference.
# Columns: bytes/sha256_16 measured with coreutils; c, k, genomes,
# min_genome_kmers, below_floor read back from 'syldb-reduce --list'.
# below_floor counts sketches with fewer than $FLOOR genome_kmers, which profile()
# can never report; it must be 0 in a shipped build. The genome count DIFFERENCE
# between two variants is exactly the genomes the coarser c pushed under that floor.
# CAVEAT (unfixed, do not read these counts as species counts): dereplication
# across catalogues is by GTDB species name, and 23312 of the 56782 merged genomes
# (41.1%) carry no species name — novel species, overwhelmingly soil (10348),
# marine (5796) and marine-sediment (2050). Two unnamed genomes from two
# catalogues may be the same organism; nothing here can tell. Those biomes are
# therefore over-represented by an unknown amount, and a screening verdict for
# them is a floor, not a figure. See sylph-wasm/src/bin/syldb-reduce.rs.
EOF
printf 'file\tc\tk\tgenomes\tbytes\tsha256_16\tmin_genome_kmers\tbelow_floor\tnote\n'

for f in "${FILES[@]}"; do
  line="$("$REDUCE" --list --min-kmers "$FLOOR" "$f" | head -1)"
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$(basename "$f")" \
    "$(field "$line" c)" \
    "$(field "$line" k)" \
    "$(field "$line" n)" \
    "$(stat -c%s "$f")" \
    "$(sha256sum "$f" | cut -c1-16)" \
    "$(field "$line" min_genome_kmers)" \
    "$(field "$line" below_floor)" \
    "$(note_for "$f")"
done
